Sprint 1
dmrgv/middle.messenger.praktikum.yandex pull request #1
Opened 2021-11-20 22:16 UTC by dmrgv

Экраны: логин, регистрация, профиль, список чатов - пока верстка в первом приближении.
На экране профиля смену пароля планирую реализовать с помощью одного поля с иконкой просмотра.
Кнопка сохранить будет не активна, пока не внесли изменения.

2021-11-21 12:49 UTC, avdoshenkov requested changes
Хорошая работа!

Несколько моментов можно доработать, и проект будет готов для следующего этапа.

2021-11-21 12:49 UTC, avdoshenkov commented on README.md
> +Ссылка на PR: https://github.com/dmrgv/middle.messenger.praktikum.yandex/pull/1
Не хватает ссылок на макет дизайна и Netlify

2021-11-21 12:49 UTC, avdoshenkov commented on app.js
> +const PORT = 3000;
Здесь можно порт указать таким образом:
```suggestion
const PORT = process.env.PORT || 3000; 
```
Тогда будет возможность брать значение из env-переменных, а уже если там её не окажется, то брать значение по умолчанию

2021-11-21 12:49 UTC, avdoshenkov commented on src/pages/404/notfound-template.js
> +export const notFoundTemplate = `<div class='align-center'>
Здесь и в других компонентах можно разделить первую часть имени также дефисом, например, `not-found-template`. Или `not-found.template`. В любом случае так читаемость будет получше

2021-11-21 12:49 UTC, avdoshenkov commented on src/pages/chats/chats-template.js
> +      </a>
Меня смущает вложенность блочных `div`-ов в строчный элемент `a`. [Лучше](https://doka.guide/html/a/#alyona-batickaya) спустить ссылку вглубь блочного элемента

2021-11-21 12:49 UTC, avdoshenkov commented on src/pages/chats/chats.scss
> +    background-color: #fbfbfb;
Удобно использовать цвета, шрифты и прочие повторяющиеся вещи в виде переменных. Их можно вынести в одно место, и если по дизайну в будущем что-то изменится, достаточно будет в одном месте изменить значение. Зато эффект будет виден по всей системе одновременно

2021-11-21 12:49 UTC, avdoshenkov commented on src/pages/login/login-template.js
> +        <input name='{{this.inputName}}' type='{{this.type}}' />
Не хватает, как минимум, атрибута id у поля ввода, который послужит для связки с `<label>`. И вообще будет отлично, если изменишь `<span>` на `<label>`. Подробнее про это можно почитать [тут](https://doka.guide/html/label/#na-praktike). Это касается всего приложения

2021-11-21 12:49 UTC, avdoshenkov commented on src/pages/login/login-template.js
> +      <button id='login-sign-up' class="link"><a href="./register.html">Нет аккаунта?</a></button>
Если по поведению элемент именно ссылка, то чтобы применить к нему стили кнопки, достаточно вынести эти стили в CSS класс, и применять по необходимости. Вот [здесь](https://doka.guide/html/button/#alyona-batickaya) подробнее. Это тоже касается всего приложения

2021-11-21 12:49 UTC, avdoshenkov commented on src/pages/profile/profile-template.js
> +          <button id='profile-save' disabled='disabled'>Сохранить</button>
Если в дальнейшем где-то останутся кнопки, то важно не забыть про различные [типы](https://doka.guide/html/button/#atributy) кнопок. Т.к. тип по-умолчанию `submit` вызовет отправку формы, а для кнопки «Назад» это точно неправильное поведение

2021-11-21 12:49 UTC, avdoshenkov commented on src/pages/profile/profile-template.js
> +  <div class="profile-block">
В дальнейшем здесь нужно будет добавить форму вокруг контента, т.к. будет отправка на сервер

2021-11-22 17:16 UTC, dmrgv commented on README.md
> +Ссылка на PR: https://github.com/dmrgv/middle.messenger.praktikum.yandex/pull/1
Макеты выложены в каталоге ui в корне проекта. Дизайн в Figma от Практикума. Пока не удается задеплоить на Netlify. По остальным замечаниям постарался все учесть. Спасибо!

2021-11-26 17:46 UTC, avdoshenkov approved these changes
Отлично! Можно двигаться дальше

2021-11-26 18:17 UTC, dmrgv commented
Спасибо за оперативную проверку!

2021-11-27 13:32 UTC, merged